name: JSDocs CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: Push services directory to another repository to build JSDoc separately.
      uses: johnhanlon86/flux@push-services-directory-to-another-repo-to-build-jsdocs-separately
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'ZelBack/src/services/'
        destination-github-username: 'johnhanlon86'
        destination-repository-name: 'fluxjsdocs'
        user-email: johnhanlon86@gmail.com
        user-name: 'johnhanlon86'
        target-branch: main
